### ISSUE TITLE
Deleting Logs doesnt remove them from the log list immediately

### ISSUE THREAD

**Issue by therealketchup** [therealketchup/evtc#1]
After deleting Logs the List of logs does not refresh automatically, which it should do.

Fix Idea: pass the LogList element down to the DeleteFilesForm and call the ReloadData() method on it after deleting and before closing the window.

**Comment by therealketchup** [comment]
To enable deleting files for testing, uncomment this line
![image](https://user-images.githubusercontent.com/66785471/116010512-abb69a00-a61f-11eb-88c4-2409f66dbbb6.png)

make sure to Save a Backup of your current logs before randomly deleting stuff to test ;)

**Comment by therealketchup** [comment]
To enable deleting, uncomment this line in the DeleteFilesForm 
![image](https://user-images.githubusercontent.com/66785471/116010556-ffc17e80-a61f-11eb-9e70-78f23194dd3c.png)

make sure to back up your logs before testing ;)

**Comment by Linkaaaaa** [comment]
![2581](https://user-images.githubusercontent.com/23245218/116137909-73bd5e80-a6d4-11eb-8182-8db443db63ee.png)
LogList row 90, should be the solution

**Comment by therealketchup** [comment]
Its part of the solution but I am still unsure on how to call that method.

1. I could make the LogDetailPanel and MultipleLogPanel keep track of their parent (LogList) and then set up an event that gets called when the DeleteFilesForm gets closed
or
2. Create an EventHandler in LogDetailPanel and MultipleLogPanel, which will Invoke a new Event when the DeleteFilesForm gets closed which I bind a method that calls the ReloadData() to.

**Comment by therealketchup** [comment]
found a way better solution, 
f9b1988dd5534bc4c9f7556ad5e4e110cd34d8b1 fixes this
