### ISSUE TITLE
In DeleteFilesForm the bosses names need to have spaces between the words

### ISSUE THREAD

**Issue by Linkaaaaa** [therealketchup/evtc#4]
Currently bosses names such as "Ai, Keeper of the Peak" are displayed as "AiKeeperofthePeak"

**Comment by therealketchup** [comment]
Can be done using an ILogNameProvider
example in Sections\LogList.cs
![image](https://user-images.githubusercontent.com/66785471/116100559-5628ce80-a6ad-11eb-9144-e1d5607eac87.png)
