### ISSUE TITLE
Upon log deletion, locate the file name in the cache file and delete the string

### ISSUE THREAD

**Issue by Linkaaaaa** [therealketchup/evtc#7]

**Comment by therealketchup** [comment]
We might be able to use the Prune method in the log cache.

Not 100% sure what the best approach is, we could also write a new method in the log cache that takes a list of deleted Logs instead of Prune which takes a list of kept logs.

**Comment by therealketchup** [comment]
This issue might be related to #1

**Comment by Linkaaaaa** [comment]
No longer necessary
